#!/usr/bin/env bash
# Configures NGINX
#!/bin/bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Create index.html file with "Hello World!" message
sudo echo "Hello World!" > /var/www/html/index.html

# Restart Nginx using /etc/init.d/nginx
sudo /etc/init.d/nginx restart
