#!/usr/bin/env bash
# Configures NGINX
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
new_direct="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sed -i "s/server_name _;/$new_direct/" /etc/nginx/sites-enabled/default
sudo service nginx start
