#!/usr/bin/env bash
# Configures NGINX
sudo apt-get update
sudo apt-get install -y nginx
sudo chmod o+w /var/www/html/
echo "Ceci n'est pas une page" > /var/www/html/404.html
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

sudo chmod o+w /etc/nginx/sites-enabled/
echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
