#!/usr/bin/env bash
# Installs HAproxy and configures it
sudo apt-get update -y
sudo apt-get install -y haproxy

CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 128822-web-01 52.23.178.94:80 check
	server 128822-web-02 100.26.225.39:80 check
"

sudo chmod o+w /etc/haproxy/haproxy.cfg
sudo chmod o+w /etc/default/haproxy
echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy start
