#!/usr/bin/env bash
#displays best school 10 times using while loop
# displays hi on the 9th iteration

number=1
while [ $number -le 10 ]
do
	echo "Best School"
	if [ $number -eq 9 ]
	then
		echo "Hi"
	fi
	number=$(( number+1 ))
done
