#!/usr/bin/env bash
#changes user to nginx

chmod 604 /etc/nginx/nginx.conf
nginx_config_file="/etc/nginx/nginx.conf"
sed -i 's/user\s\+\w\+/user nginx/' "$nginx_config_file"
nginx_default_server_config_file="/etc/nginx/conf.d/default.conf"
sed -i 's/listen\s\+\w\+;/listen 8080;/' "$nginx_default_server_config_file"
sudo -u nginx service nginx restart
